In [3]:

import numpy as np

In [4]:
arr = np.arange(10)


In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[5:8]

array([5, 6, 7])

In [7]:
arr[5:8] = 12

In [8]:
arr


array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [9]:
arr_slice = arr[5:8]


In [10]:
arr_slice

array([12, 12, 12])

In [11]:
arr_slice[1] = 12345

In [12]:
arr  #slice ko view creating bi bolta ha.xais 0 means xais

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [16]:
arr2=np.arange(1,25).reshape(6,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [27]:
arr2[2:5,2:4]

array([[11, 12],
       [15, 16],
       [19, 20]])

In [25]:
arr2[0:,2]

array([ 3,  7, 11, 15, 19, 23])

In [28]:
arr2[2:,1:3]

array([[10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [33]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [36]:
a=arr2[2,1:3]
a


array([10, 11])

In [37]:
b=arr2[5,1:3]
b

array([22, 23])

In [41]:
arr2[3]


array([13, 14, 15, 16])

In [42]:
arr2[:,3]

array([ 4,  8, 12, 16, 20, 24])

In [43]:
arr2[2,3]

12

In [44]:
arr2[[1,4]] #2 row alag chaye tu list ka andar dana hoga

array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]])

In [51]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [50]:
arr2[[1,4],[1,2]]  #order piar banaye ga

array([ 6, 19])

In [52]:
#boolean indexing 
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])



In [53]:
data = np.random.randn(7, 4)


In [54]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [55]:
data

array([[ 1.02546463, -0.15808924, -0.14097612, -0.45846065],
       [-0.13141838, -0.72674401,  1.34164573,  1.08001541],
       [-1.23530937, -0.66969408,  0.19492547,  0.78789348],
       [-0.28170576,  1.00721296,  0.10201846,  2.40956438],
       [-0.8214477 , -0.47991723,  0.25768493,  0.01701057],
       [-1.82925075,  1.0898605 , -0.41906815,  0.33846863],
       [-0.98071841,  1.4928801 ,  0.61053876,  0.33135407]])

In [56]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [57]:
data[names == 'Bob']

array([[ 1.02546463, -0.15808924, -0.14097612, -0.45846065],
       [-0.28170576,  1.00721296,  0.10201846,  2.40956438]])

In [58]:
data[names == 'Bob', 2:]

array([[-0.14097612, -0.45846065],
       [ 0.10201846,  2.40956438]])

In [59]:
data[names == 'Bob', 3]

array([-0.45846065,  2.40956438])

In [62]:
names!='Bob'

array([False,  True,  True, False,  True,  True,  True])

In [64]:
data

array([[ 1.02546463, -0.15808924, -0.14097612, -0.45846065],
       [-0.13141838, -0.72674401,  1.34164573,  1.08001541],
       [-1.23530937, -0.66969408,  0.19492547,  0.78789348],
       [-0.28170576,  1.00721296,  0.10201846,  2.40956438],
       [-0.8214477 , -0.47991723,  0.25768493,  0.01701057],
       [-1.82925075,  1.0898605 , -0.41906815,  0.33846863],
       [-0.98071841,  1.4928801 ,  0.61053876,  0.33135407]])

In [63]:
data[~(names=='Bob')]

array([[-0.13141838, -0.72674401,  1.34164573,  1.08001541],
       [-1.23530937, -0.66969408,  0.19492547,  0.78789348],
       [-0.8214477 , -0.47991723,  0.25768493,  0.01701057],
       [-1.82925075,  1.0898605 , -0.41906815,  0.33846863],
       [-0.98071841,  1.4928801 ,  0.61053876,  0.33135407]])

In [67]:
arr>15   #true false ma aye ga


array([False, False, False, False, False, False,  True, False, False,
       False])

In [68]:
data[data < 0] = 0
data


array([[1.02546463, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.34164573, 1.08001541],
       [0.        , 0.        , 0.19492547, 0.78789348],
       [0.        , 1.00721296, 0.10201846, 2.40956438],
       [0.        , 0.        , 0.25768493, 0.01701057],
       [0.        , 1.0898605 , 0.        , 0.33846863],
       [0.        , 1.4928801 , 0.61053876, 0.33135407]])

In [69]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 1.34164573, 1.08001541],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.0898605 , 0.        , 0.33846863],
       [0.        , 1.4928801 , 0.61053876, 0.33135407]])

In [72]:
cond = names == 'Bob'
cond

array([ True, False, False,  True, False, False, False])

In [73]:
data[~cond]


array([[0.        , 0.        , 1.34164573, 1.08001541],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.0898605 , 0.        , 0.33846863],
       [0.        , 1.4928801 , 0.61053876, 0.33135407]])

In [74]:
data[cond]

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [76]:
names


array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [75]:
mask = (names == 'Bob') | (names == 'Will')
mask


array([ True, False,  True,  True,  True, False, False])

In [78]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 1.34164573, 1.08001541],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.0898605 , 0.        , 0.33846863],
       [0.        , 1.4928801 , 0.61053876, 0.33135407]])

In [77]:
data[mask]


array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [79]:
data[~(mask)]

array([[0.        , 0.        , 1.34164573, 1.08001541],
       [0.        , 1.0898605 , 0.        , 0.33846863],
       [0.        , 1.4928801 , 0.61053876, 0.33135407]])

In [70]:
#fancy indexing  

In [80]:
arr = np.empty((8, 4))

In [81]:
for i in range(8):
     arr[i] = i

In [82]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [83]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [84]:
arr[[-3, -5, -7]] #ulti indexing chalti ha 0 sa nhi 1 sa chala ga

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [ ]:
arr[[r1,r2]][[c1,2]] #syntax

In [85]:
arr = np.arange(32).reshape((8, 4))

In [86]:
arr


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [87]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]  #order pair 


array([ 4, 23, 29, 10])

In [88]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]  # ya matrix multiply ki tarha hoga 1 phla sab sa hoga means 0,3,1,2 q ka huma : lagya ha tu 4*4 ha tu 16 pair hoga
#fancy sa copy banti ha 

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [90]:
arr = np.arange(15).reshape((3, 5))
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [91]:
arr.T


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [92]:
arr = np.random.randn(6, 3)

In [93]:
np.dot(arr.T, arr)  #transport sa multiply

array([[12.69271269,  4.65413572,  2.12089589],
       [ 4.65413572,  6.5648291 , -1.77960274],
       [ 2.12089589, -1.77960274,  6.45386589]])

In [94]:
10/2

5.0

In [95]:
10//2

5

In [ ]:
#cumsum  haar num ma agala plus karo
#standard devaition mean sa kitne door ha  average age ma sa orignal minus karo
# devaition ka square 
#any kiya koi value ya ha

In [96]:
a=[1,2,3,4,5]

In [97]:
s=set(a)
s 
#unique aye gi ya any function istemal karo
#qr quotient remainder ka function ha
#daignal ka sara element ko plus karta ha trace

{1, 2, 3, 4, 5}

In [100]:
s={1,1,14,5}
s

{1, 5, 14}

In [121]:
arr = np.arange(32)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [122]:
arr=arr.reshape(4,8)

arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [123]:
flat1=arr.flatten() #multidimension sa single hogaya

In [124]:
flat1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [125]:
flat1[1]=100 #flat copy bnata ha
flat1

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31])

In [126]:
arr  # orignal pa farak nhi parha

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [127]:
r=arr.ravel()
r[1]=100
r

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31])

In [128]:
arr


array([[  0, 100,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31]])

In [129]:
arr  # orignal pa farak nhi parha

array([[  0, 100,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31]])

In [131]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [132]:
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [134]:
np.concatenate([arr1, arr2]) #axis 0 pa izafa hoga tu row increse hogi


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [135]:
np.concatenate([arr1, arr2], axis=1)#axis 1 tu columnn ma izafa hoga vertical barhana ha tu row barhao warna column horizontal mma
                                        

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [137]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [138]:
np.vstack((arr1, arr2))
#row barha gi

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [139]:
np.hstack((arr1, arr2))
#column barha gi

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [141]:
arr = np.random.randn(5, 2)
arr

array([[ 0.30083316, -0.78768579],
       [ 1.93316924, -0.72528334],
       [-0.64463051,  1.44122512],
       [-1.57624378, -1.04194127],
       [-0.26454604, -0.99020715]])

In [142]:
first, second, third = np.split(arr, [1, 3])

In [143]:
first


array([[ 0.30083316, -0.78768579]])

In [144]:
second

array([[ 1.93316924, -0.72528334],
       [-0.64463051,  1.44122512]])

In [145]:
third

array([[-1.57624378, -1.04194127],
       [-0.26454604, -0.99020715]])

In [146]:
arr1=np.arange(12).reshape(4,3)
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [147]:
np.vsplit(arr1,4)


[array([[0, 1, 2]]),
 array([[3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11]])]

In [148]:
np.vsplit(arr1,2) #3 ma error 

[array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [155]:
np.hsplit(arr1,3)   #SAME PA SPLIT HOGA MEAN 4*4 MATRIX HA TU ROW KA LIYA 2 BY 2 HO SAKTA HA 3 NHI
#DSTACK 3 DIMENSION MA USE HOTA HA

[array([[0],
        [3],
        [6],
        [9]]), array([[ 1],
        [ 4],
        [ 7],
        [10]]), array([[ 2],
        [ 5],
        [ 8],
        [11]])]

In [156]:
arr=np.arange(3)
arr



array([0, 1, 2])

In [159]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [164]:
arr.repeat([2,3,4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [165]:
np.tile(arr,2)

array([0, 1, 2, 0, 1, 2])

In [ ]:
#fortan =column
#corder=row
#broadast unsame matrix add kardo vector apna ap ko repaet karta ka same hojae

In [168]:
arr = np.arange(5)

arr

array([0, 1, 2, 3, 4])

In [169]:
arr * 4

array([ 0,  4,  8, 12, 16])

In [170]:
arr = np.random.randn(4, 3)


In [171]:
arr.mean(0)


array([-0.14883268, -0.3405699 ,  0.22346788])