In [1]:
import numpy as np

In [2]:
arr1=np.zeros((3,4))
arr1



array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
arr2=np.ones_like(arr1)
arr2


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
arr3=np.arange(16)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
arr3.ndim

1

In [8]:
a=arr3.reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
arr3.shape=(8,2)
arr3

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [11]:
arr3.resize(4,4)
arr3 #inplace karta ha 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
arr3.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [20]:
arr4=np.arange(10,501,10).reshape(10,5) # 10 ka step rakha ga
arr4

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250],
       [260, 270, 280, 290, 300],
       [310, 320, 330, 340, 350],
       [360, 370, 380, 390, 400],
       [410, 420, 430, 440, 450],
       [460, 470, 480, 490, 500]])

In [21]:
len(arr4)

10

In [22]:
arr4**2

array([[   100,    400,    900,   1600,   2500],
       [  3600,   4900,   6400,   8100,  10000],
       [ 12100,  14400,  16900,  19600,  22500],
       [ 25600,  28900,  32400,  36100,  40000],
       [ 44100,  48400,  52900,  57600,  62500],
       [ 67600,  72900,  78400,  84100,  90000],
       [ 96100, 102400, 108900, 115600, 122500],
       [129600, 136900, 144400, 152100, 160000],
       [168100, 176400, 184900, 193600, 202500],
       [211600, 220900, 230400, 240100, 250000]], dtype=int32)

In [23]:
arr4

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250],
       [260, 270, 280, 290, 300],
       [310, 320, 330, 340, 350],
       [360, 370, 380, 390, 400],
       [410, 420, 430, 440, 450],
       [460, 470, 480, 490, 500]])

In [26]:
arr5=arr4[0:5,:]
arr5

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

In [28]:
arr5=arr5*2
arr5


array([[  40,   80,  120,  160,  200],
       [ 240,  280,  320,  360,  400],
       [ 440,  480,  520,  560,  600],
       [ 640,  680,  720,  760,  800],
       [ 840,  880,  920,  960, 1000]])

In [29]:
arr4

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250],
       [260, 270, 280, 290, 300],
       [310, 320, 330, 340, 350],
       [360, 370, 380, 390, 400],
       [410, 420, 430, 440, 450],
       [460, 470, 480, 490, 500]])

In [32]:
arr6=arr4[[0,1,-2,-1],:]
arr6

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [410, 420, 430, 440, 450],
       [460, 470, 480, 490, 500]])

In [35]:
arr6=arr4[[0,1,-2,-1],0:2]
arr6

array([[ 10,  20],
       [ 60,  70],
       [410, 420],
       [460, 470]])

In [36]:
arr4[::2]

array([[ 10,  20,  30,  40,  50],
       [110, 120, 130, 140, 150],
       [210, 220, 230, 240, 250],
       [310, 320, 330, 340, 350],
       [410, 420, 430, 440, 450]])

In [37]:
arr4[::-1]

array([[460, 470, 480, 490, 500],
       [410, 420, 430, 440, 450],
       [360, 370, 380, 390, 400],
       [310, 320, 330, 340, 350],
       [260, 270, 280, 290, 300],
       [210, 220, 230, 240, 250],
       [160, 170, 180, 190, 200],
       [110, 120, 130, 140, 150],
       [ 60,  70,  80,  90, 100],
       [ 10,  20,  30,  40,  50]])

In [38]:
arr4[::-1,::-1]

array([[500, 490, 480, 470, 460],
       [450, 440, 430, 420, 410],
       [400, 390, 380, 370, 360],
       [350, 340, 330, 320, 310],
       [300, 290, 280, 270, 260],
       [250, 240, 230, 220, 210],
       [200, 190, 180, 170, 160],
       [150, 140, 130, 120, 110],
       [100,  90,  80,  70,  60],
       [ 50,  40,  30,  20,  10]])

In [40]:
np.vsplit(arr4,2)


[array([[ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100],
        [110, 120, 130, 140, 150],
        [160, 170, 180, 190, 200],
        [210, 220, 230, 240, 250]]), array([[260, 270, 280, 290, 300],
        [310, 320, 330, 340, 350],
        [360, 370, 380, 390, 400],
        [410, 420, 430, 440, 450],
        [460, 470, 480, 490, 500]])]

In [39]:
arr6,arr7=np.vsplit(arr4,2) #half karda ga q ka 2 dala ha


In [41]:
arr6

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

In [42]:
arr7


array([[260, 270, 280, 290, 300],
       [310, 320, 330, 340, 350],
       [360, 370, 380, 390, 400],
       [410, 420, 430, 440, 450],
       [460, 470, 480, 490, 500]])

In [43]:
np.hstack((arr6,arr7)) #concetinate horizontal vertical mean oposite

array([[ 10,  20,  30,  40,  50, 260, 270, 280, 290, 300],
       [ 60,  70,  80,  90, 100, 310, 320, 330, 340, 350],
       [110, 120, 130, 140, 150, 360, 370, 380, 390, 400],
       [160, 170, 180, 190, 200, 410, 420, 430, 440, 450],
       [210, 220, 230, 240, 250, 460, 470, 480, 490, 500]])

In [44]:
np.stack((arr6,arr7),axis=1) #concatinate same

array([[[ 10,  20,  30,  40,  50],
        [260, 270, 280, 290, 300]],

       [[ 60,  70,  80,  90, 100],
        [310, 320, 330, 340, 350]],

       [[110, 120, 130, 140, 150],
        [360, 370, 380, 390, 400]],

       [[160, 170, 180, 190, 200],
        [410, 420, 430, 440, 450]],

       [[210, 220, 230, 240, 250],
        [460, 470, 480, 490, 500]]])

In [55]:
np.stack((arr6,arr7),axis=0) #concatinate same

array([[[ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100],
        [110, 120, 130, 140, 150],
        [160, 170, 180, 190, 200],
        [210, 220, 230, 240, 250]],

       [[260, 270, 280, 290, 300],
        [310, 320, 330, 340, 350],
        [360, 370, 380, 390, 400],
        [410, 420, 430, 440, 450],
        [460, 470, 480, 490, 500]]])

In [45]:
np.vsplit(arr4,5)

[array([[ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100]]), array([[110, 120, 130, 140, 150],
        [160, 170, 180, 190, 200]]), array([[210, 220, 230, 240, 250],
        [260, 270, 280, 290, 300]]), array([[310, 320, 330, 340, 350],
        [360, 370, 380, 390, 400]]), array([[410, 420, 430, 440, 450],
        [460, 470, 480, 490, 500]])]

In [46]:
np.hsplit(arr4,5) # split nhi honga

[array([[ 10],
        [ 60],
        [110],
        [160],
        [210],
        [260],
        [310],
        [360],
        [410],
        [460]]), array([[ 20],
        [ 70],
        [120],
        [170],
        [220],
        [270],
        [320],
        [370],
        [420],
        [470]]), array([[ 30],
        [ 80],
        [130],
        [180],
        [230],
        [280],
        [330],
        [380],
        [430],
        [480]]), array([[ 40],
        [ 90],
        [140],
        [190],
        [240],
        [290],
        [340],
        [390],
        [440],
        [490]]), array([[ 50],
        [100],
        [150],
        [200],
        [250],
        [300],
        [350],
        [400],
        [450],
        [500]])]

# indexing

In [50]:
arr3=np.arange(1,25).reshape(2,3,4)
arr3 #24 total 


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [54]:
arr3[1][1][2]

19

In [56]:
arr3[1,1,2]

19

In [58]:
arr3[1][0:2,1:3]

array([[14, 15],
       [18, 19]])

In [61]:
arr3[0,2,2:4]

array([11, 12])

In [62]:
arr3[1,:2,1:-1]

array([[14, 15],
       [18, 19]])

In [63]:
arr3[0,-1,2:]

array([11, 12])

In [84]:
arr3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [68]:
arr3[1,::2,::2]

array([[13, 15],
       [21, 23]])

In [83]:
arr3[1,0::2,0:3:2] #:: beach ma ak row drop karni ha

array([[13, 15],
       [21, 23]])

In [77]:
arr3[1,[0,2],0:3:2]

array([[13, 15],
       [21, 23]])

In [78]:
arr4=np.arange(100).reshape(4,5,5)

In [79]:
arr4

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [80]:
arr4[2:4,:,:]

array([[[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [ ]:
#NUMPY NUMERICAL DATA PA KAM KARTI HA 
#PANDAS HAAR PA KAM KARTA HA 

# PANDAS

In [85]:
import pandas as pd

In [86]:
from pandas import Series, DataFrame
#pandas ka data structure ha series ,frames

In [ ]:
#A Series is a one-dimensional array-like object containing a sequence of values (of
#similar types to NumPy types) and an associated array of data labels, called its index.
#The simplest Series is formed from only an array of data:

In [88]:
obj = pd.Series([4, 7.8, -5, 3]) #series ka object
obj #series ka sath indexing bi arahi ha

0    4.0
1    7.8
2   -5.0
3    3.0
dtype: float64

In [89]:
type(obj)

pandas.core.series.Series

In [90]:
obj.values

array([ 4. ,  7.8, -5. ,  3. ])

In [91]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [92]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [93]:
obj2['d'] #same index hoga tu 2no values aye gi

4

In [95]:
obj2['c']

3

In [97]:
obj2['d'] = 6
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [98]:
obj2[['c', 'a', 'd']]


c    3
a   -5
d    6
dtype: int64

In [99]:
obj2[obj2 > 0]


d    6
b    7
c    3
dtype: int64

In [100]:
obj2 * 2


d    12
b    14
a   -10
c     6
dtype: int64

In [101]:
obj2>0

d     True
b     True
a    False
c     True
dtype: bool

In [102]:
'b' in obj2

True

In [103]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [104]:
'e' in obj2

False

In [134]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
sdata
#converting dict to series

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [110]:
type(sdata)

dict

In [107]:
obj3 = pd.Series(sdata)

In [108]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [109]:
type(obj3)

pandas.core.series.Series

In [130]:
states = ['California', 'Ohio', 'Oregon', 'Texas'] #jis order ma chaye uski list bana li

In [131]:
obj4 = pd.Series(sdata, index=states)
obj4 # california nhi sdata ma isliye nan nan mean not a number

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [132]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [133]:
pd.notnull(obj4)


California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [136]:
sdata

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [135]:
pd.isnull(sdata)

False

In [127]:
pd.isnull(obj4)


California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [128]:
pd.notnull(obj4)


California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [129]:
pd.notnull(sdata)


True

In [139]:
sdata1=obj4.copy()
sdata1

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [144]:
sdata1['California'],sdata1['Ohio']=sdata1['Ohio'],sdata1['California'] #swap
sdata1['karachi']=10000

In [145]:
sdata1

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
karachi       10000.0
dtype: float64

In [147]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [146]:
obj4+sdata1 #nan ka sath koi operation nhi hoga karachi nan isliye ha ka koi value nhi

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
karachi            NaN
dtype: float64

In [152]:
sdata1.index

Index(['California', 'Ohio', 'Oregon', 'Texas', 'karachi'], dtype='object')

# data frames

In [153]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}


In [154]:
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [155]:
type(frame)

pandas.core.frame.DataFrame

In [156]:
frame['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [157]:
frame['year']

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [158]:
frame.head(1) #1 mean kitne row

state  year  pop
0  Ohio  2000  1.5

In [160]:
frame.head() # 5 start by default

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [159]:
frame.tail() #5 last five 

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [187]:
pd.DataFrame(data, columns=[ 'state', 'pop'])


state  pop
0    Ohio  1.5
1    Ohio  1.7
2    Ohio  3.6
3  Nevada  2.4
4  Nevada  2.9
5  Nevada  3.2

In [191]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
index=['one', 'two', 'three', 'four',
 'five', 'six'])
frame2['debt']=range(1,7)
#range ka andar list bi pass kar sakt ha
frame2


year   state  pop  debt
one    2000    Ohio  1.5     1
two    2001    Ohio  1.7     2
three  2002    Ohio  3.6     3
four   2001  Nevada  2.4     4
five   2002  Nevada  2.9     5
six    2003  Nevada  3.2     6

In [163]:
frame2 #index same rakhni ha warna error

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [171]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [189]:
frame2.loc['one':'four':2] # 2 step ha 

year state  pop  debt
one    2000  Ohio  1.5   NaN
three  2002  Ohio  3.6   NaN

In [174]:
frame2.loc['one']

year     2000
state    Ohio
pop       1.5
debt        1
Name: one, dtype: object

In [175]:
frame2.loc['one']['state']

'Ohio'

In [176]:
frame2.loc['one':'three'] #loc inclusive ha ya is ma number jab pass karna jb index number ho

year state  pop  debt
one    2000  Ohio  1.5     1
two    2001  Ohio  1.7     2
three  2002  Ohio  3.6     3

In [177]:
frame2.iloc[0:2] # iloc exclusive numerical indexing use karta ha

year state  pop  debt
one  2000  Ohio  1.5     1
two  2001  Ohio  1.7     2

In [178]:
frame.loc[0:2]

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7
2  Ohio  2002  3.6

In [185]:
val = pd.Series([-1.2, -1.5, -1.7,7], index=['two', 'four', 'five','seven'])
val


two     -1.2
four    -1.5
five    -1.7
seven    7.0
dtype: float64

In [192]:
frame2['debt1'] = val
frame2

year   state  pop  debt  debt1
one    2000    Ohio  1.5     1    NaN
two    2001    Ohio  1.7     2   -1.2
three  2002    Ohio  3.6     3    NaN
four   2001  Nevada  2.4     4   -1.5
five   2002  Nevada  2.9     5   -1.7
six    2003  Nevada  3.2     6    NaN

In [193]:
frame2['debt1']['six']=12
frame2

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


year   state  pop  debt  debt1
one    2000    Ohio  1.5     1    NaN
two    2001    Ohio  1.7     2   -1.2
three  2002    Ohio  3.6     3    NaN
four   2001  Nevada  2.4     4   -1.5
five   2002  Nevada  2.9     5   -1.7
six    2003  Nevada  3.2     6   12.0

In [194]:
frame2['debt1']['six','one']=13,14
frame2

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:190: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


year   state  pop  debt  debt1
one    2000    Ohio  1.5     1   14.0
two    2001    Ohio  1.7     2   -1.2
three  2002    Ohio  3.6     3    NaN
four   2001  Nevada  2.4     4   -1.5
five   2002  Nevada  2.9     5   -1.7
six    2003  Nevada  3.2     6   13.0

In [195]:
frame2['eastern'] = frame2.state == 'Ohio'#data available,data calulated 2 type of data ya calculating data ha q ka jis pa kam kar raha usko use karta wa column genearte karaya
frame2   

year   state  pop  debt  debt1  eastern
one    2000    Ohio  1.5     1   14.0     True
two    2001    Ohio  1.7     2   -1.2     True
three  2002    Ohio  3.6     3    NaN     True
four   2001  Nevada  2.4     4   -1.5    False
five   2002  Nevada  2.9     5   -1.7    False
six    2003  Nevada  3.2     6   13.0    False

In [196]:
del frame2['eastern']

In [197]:
frame2

year   state  pop  debt  debt1
one    2000    Ohio  1.5     1   14.0
two    2001    Ohio  1.7     2   -1.2
three  2002    Ohio  3.6     3    NaN
four   2001  Nevada  2.4     4   -1.5
five   2002  Nevada  2.9     5   -1.7
six    2003  Nevada  3.2     6   13.0

In [222]:
frame2['eastern']=["Pass" if i=="Ohio" else "Fail" for i in frame2.state]
frame2

year   state  pop  debt  debt1 eastern
one    2000    Ohio  1.5     1   14.0    Pass
two    2001    Ohio  1.7     2   -1.2    Pass
three  2002    Ohio  3.6     3    NaN    Pass
four   2001  Nevada  2.4     4   -1.5    Fail
five   2002  Nevada  2.9     5   -1.7    Fail
six    2003  Nevada  3.2     6   13.0    Fail

In [199]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [200]:
frame3 = pd.DataFrame(pop)

In [201]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [202]:
data1 = {'student': ['shakeeb', 'sami', 'shoaib'],
 'class': [8, 9, 10],
 'roll': [25, 23, 6]}


In [203]:
data1


{'student': ['shakeeb', 'sami', 'shoaib'],
 'class': [8, 9, 10],
 'roll': [25, 23, 6]}

In [204]:

frame1 = pd.DataFrame(data1)
frame1

student  class  roll
0  shakeeb      8    25
1     sami      9    23
2   shoaib     10     6

In [206]:
frame1['class']

0     8
1     9
2    10
Name: class, dtype: int64

In [207]:
frame1.head()

student  class  roll
0  shakeeb      8    25
1     sami      9    23
2   shoaib     10     6

In [209]:
frame1.columns

Index(['student', 'class', 'roll'], dtype='object')

In [210]:
frame1.index

RangeIndex(start=0, stop=3, step=1)

In [213]:
frame1.tail()

student  class  roll
0  shakeeb      8    25
1     sami      9    23
2   shoaib     10     6

In [ ]:
frame1['Attendence']=["Pass" if i=="Ohio" else "Fail" for i in frame2.roll]
frame2

In [216]:
frame1.loc[0]

student    shakeeb
class            8
roll            25
Name: 0, dtype: object

In [217]:
frame1.loc[1]

student    sami
class         9
roll         23
Name: 1, dtype: object

In [219]:
frame1.loc[0,'student']

'shakeeb'

In [227]:
data ={
    "Math":[90,89,78,32,76],
    "physics":[23,45,78,90,34],
    "chemistry":[32,34,67,89,88]
    
}
frame3=pd.DataFrame(data,index=['std1','std2','std3','std4','std5'])
frame3

Math  physics  chemistry
std1    90       23         32
std2    89       45         34
std3    78       78         67
std4    32       90         89
std5    76       34         88

In [235]:
frame3['total']=[m+p+c for m,p,c in zip(frame3['Math'],frame3['physics'],frame3['chemistry'])
frame3['remarks']=["pass" if m>=33 and p>=33 and c>=33 else "Fail" for m,p,c in zip(frame3['Math'],frame3['physics'],frame3['chemistry'])

SyntaxError: invalid syntax (<ipython-input-235-73e2fc23fff0>, line 2)