In [1]:
import numpy as np

In [2]:
l=range(1000000)

In [3]:
d=np.arange(1000000)

In [4]:
%time for i in range(1,10):r=[x*2 for x in l]

Wall time: 2.12 s


In [5]:
%time for i in range(1,10):r=d*2

Wall time: 71.9 ms


In [6]:
x=np.zeros((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.empty((7,7))
#randomly data

array([[ 0.00000000e+000,  6.95231506e-310,  1.74899239e-321,
                     nan,  2.58161125e-306,  4.76223221e-287,
         1.97417585e-046],
       [ 7.93544652e-301,  2.10327453e-286,  7.93544660e-301,
         1.47763649e-277,  1.34047036e-272,  2.13545392e-287,
         1.69265303e-258],
       [ 1.43962856e-277,  1.29457963e-272,  8.78727266e-268,
         2.49612439e-306,  5.20287948e-296,  1.29620431e-272,
         1.68708483e-301],
       [ 7.53790878e-244,  1.29423552e-272, -7.31469423e-114,
         2.10053206e-301,  3.48014959e-308,  3.47748437e-308,
         4.63524825e-273],
       [ 1.32122555e-228,  1.64643684e-287,  1.29397745e-272,
         1.34065087e-272,  1.63535102e-301,  8.86040129e-220,
         1.29440476e-272],
       [ 2.78137431e-308,  1.63786265e-301,  2.04564941e-277,
         1.29405083e-272,  2.43550680e-209,  3.75833466e-308,
         4.87548614e+127],
       [ 7.26883240e-249,  1.43246684e-277,  7.26883230e-249,
         2.04512008e-277,  4.229

In [9]:
l=[1,2,3,4]
np.array(l)

array([1, 2, 3, 4])

In [11]:
x=np.arange(1,100,10)

In [12]:
x.shape

(10,)

In [13]:
x=np.zeros((10,10))

In [14]:
x.shape

(10, 10)

In [15]:
y=x.reshape((2,2,5,5))
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [16]:
y.dtype

dtype('float64')

In [17]:
y.ndim

4

In [18]:
a=np.random.randn((10))
a

array([ 1.10135411, -1.26908437, -1.50634689, -0.76511902, -0.51071512,
        0.34864112,  0.08825001, -0.99561245,  4.1235976 , -0.3413169 ])

In [20]:
b=np.random.randn((10))
b

array([ 1.24564162,  1.27607876, -0.23230858, -1.24321749,  1.45491472,
        0.1256969 ,  0.56351863,  0.41282949,  1.31660832, -0.33435469])

In [21]:
a+b

array([ 2.34699573,  0.00699439, -1.73865547, -2.0083365 ,  0.9441996 ,
        0.47433802,  0.65176864, -0.58278296,  5.44020592, -0.67567158])

In [22]:
a-b

array([-0.14428751, -2.54516313, -1.27403831,  0.47809847, -1.96562984,
        0.22294422, -0.47526862, -1.40844194,  2.80698928, -0.00696221])

In [23]:
2*a

array([ 2.20270822, -2.53816874, -3.01269377, -1.53023804, -1.02143023,
        0.69728225,  0.17650001, -1.9912249 ,  8.2471952 , -0.68263379])

In [24]:
1/a #matrix inverse

array([ 0.90797318, -0.78796968, -0.66385771, -1.3069862 , -1.95803877,
        2.86827897, 11.33144394, -1.00440689,  0.24250669, -2.92982859])

In [25]:
a>0

array([ True, False, False, False, False,  True,  True, False,  True,
       False])

In [26]:
a[a>0]

array([1.10135411, 0.34864112, 0.08825001, 4.1235976 ])

In [28]:
x=np.array([1,7,9,8,4])

In [29]:
x[4]

4

In [30]:
x[x>5] #boolean indexing

array([7, 9, 8])

In [31]:
x[[2,1]] #fancy indexing

array([9, 7])

In [36]:
x=np.random.randn(10,10)
x

array([[-0.39367185,  1.37830223,  1.49919477, -0.07403711, -0.11012466,
         0.0442486 ,  1.6895714 ,  1.34291981,  0.63931103, -0.54709648],
       [-0.96325857, -2.2016917 , -1.03976436, -0.39081621,  0.63543374,
        -1.20997948,  0.03802044,  0.397083  , -0.80717686, -1.00836766],
       [ 0.07426304, -0.88989311, -0.50478549, -0.39090439,  0.10239963,
        -1.55853575, -2.02106362, -0.38095775,  0.28827174,  2.50936652],
       [-1.23677238,  1.10771634,  1.68253989,  0.15137653, -1.61073596,
         0.24135214,  0.3645883 , -0.84180194,  0.22389673, -2.06384147],
       [ 0.24899476,  1.45352168,  1.74179133, -0.04399385, -0.80606158,
         2.23589502, -0.66543609,  0.58964298,  0.50164447, -0.79045095],
       [-1.64929961,  0.27320621, -0.29457617, -0.43334314, -0.05905573,
         1.39003634,  0.67559119,  1.30580283, -0.3850103 , -1.4081052 ],
       [-1.58670135,  0.36492621,  0.51387634, -0.48719889, -2.19816682,
        -1.03509141, -0.54303103, -0.52726518

In [37]:
x[0]

array([-0.39367185,  1.37830223,  1.49919477, -0.07403711, -0.11012466,
        0.0442486 ,  1.6895714 ,  1.34291981,  0.63931103, -0.54709648])

In [38]:
x[0][4] # 0 row ka 5 element mean column

-0.11012465655698227

In [39]:
x[1:10:2] #odd rows 

array([[-0.96325857, -2.2016917 , -1.03976436, -0.39081621,  0.63543374,
        -1.20997948,  0.03802044,  0.397083  , -0.80717686, -1.00836766],
       [-1.23677238,  1.10771634,  1.68253989,  0.15137653, -1.61073596,
         0.24135214,  0.3645883 , -0.84180194,  0.22389673, -2.06384147],
       [-1.64929961,  0.27320621, -0.29457617, -0.43334314, -0.05905573,
         1.39003634,  0.67559119,  1.30580283, -0.3850103 , -1.4081052 ],
       [-1.82397065, -0.21182037,  0.32779242,  0.94159121, -0.39302765,
         0.46812601, -0.18408594, -0.01817497, -0.62573109,  0.52575078],
       [-0.37667603,  0.18801312, -1.21107237, -2.2060069 ,  0.83828823,
         1.6529251 , -0.77850858, -1.54023347,  1.11148428,  0.81443791]])

In [40]:
x[0:4,1:3]

array([[ 1.37830223,  1.49919477],
       [-2.2016917 , -1.03976436],
       [-0.88989311, -0.50478549],
       [ 1.10771634,  1.68253989]])

In [41]:
x[::,0:4]

array([[-0.39367185,  1.37830223,  1.49919477, -0.07403711],
       [-0.96325857, -2.2016917 , -1.03976436, -0.39081621],
       [ 0.07426304, -0.88989311, -0.50478549, -0.39090439],
       [-1.23677238,  1.10771634,  1.68253989,  0.15137653],
       [ 0.24899476,  1.45352168,  1.74179133, -0.04399385],
       [-1.64929961,  0.27320621, -0.29457617, -0.43334314],
       [-1.58670135,  0.36492621,  0.51387634, -0.48719889],
       [-1.82397065, -0.21182037,  0.32779242,  0.94159121],
       [-0.71258418, -2.75363179,  0.81275855,  1.21096644],
       [-0.37667603,  0.18801312, -1.21107237, -2.2060069 ]])

In [42]:
x=np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
x=np.array([10,9,8,6,11])

In [46]:
np.sqrt(x)

array([3.16227766, 3.        , 2.82842712, 2.44948974, 3.31662479])

In [48]:
np.power(x,2)

array([100,  81,  64,  36, 121], dtype=int32)

In [53]:
y=[7,1,2,3,-1]

In [54]:
np.maximum(x,y) # first ko first sa compare karaga 

array([10,  9,  8,  6, 11])

In [55]:
#np.where poraa array ko dakha ga ya tarika ternary operation ha missing fields ki value ko cover karta ha
x=np.array([0,-1,10000,5000])

In [57]:
np.where(x<=0,'not ok','ok')

array(['not ok', 'not ok', 'ok', 'ok'], dtype='<U6')

In [58]:
x=np.array([10,9,7,10,7])

In [59]:
x.mean()
#average

8.6

In [60]:
x.cumsum()
#comluative sum nikla ga is sa simple haar phala ko 2nd ma add

array([10, 19, 26, 36, 43], dtype=int32)

In [61]:
x.cumprod() 
#commulative product

array([   10,    90,   630,  6300, 44100], dtype=int32)

In [62]:
y=x>=6

In [63]:
y

array([ True,  True,  True,  True,  True])

In [64]:
y.sum()

5

In [65]:
y.any()

True

In [66]:
y.all() #sb true ha ya nhi

True

In [67]:
y=x>7
y

array([ True,  True, False,  True, False])

In [68]:
y.sum() #3 element asa ha jo true ha 

3

In [69]:
y.any()

True

In [70]:
y.all()

False

In [71]:
x

array([10,  9,  7, 10,  7])

In [72]:
x.sort()

In [73]:
x

array([ 7,  7,  9, 10, 10])

In [75]:
np.unique(x)

array([ 7,  9, 10])

In [92]:
x=np.array([1,2,3,4])

In [93]:
y=np.array([8,7,9])

In [80]:
np.save('testx',x) #single array simple is sa save honga 

In [84]:
x=np.load('testx.npy')
x

array([1, 2, 3, 4])

In [98]:
np.savez('shakeeb',x,y)

In [103]:
loadxy=np.load('shakeeb.npz')
loadxy
#ya dict ha ak tarha ki yaha .npz isliye use hoa q ka savez ka method ha

In [101]:
loadxy['y']

In [104]:
x=np.random.rand(3,2)

In [106]:
y=np.random.rand(2,3)

In [107]:
x.dot(y)

array([[0.80178582, 0.49443519, 0.27287322],
       [0.57023722, 0.27283864, 0.38318373],
       [0.84946613, 0.61073782, 0.08056912]])

In [109]:
x.transpose()

array([[0.28239293, 0.43302273, 0.04316436],
       [0.72015165, 0.35404003, 0.93735254]])

In [110]:
x.trace()

0.6364329599274064

In [111]:
#random hum isliye use karta ha ka data ki bias ko khtam karna ka liya
#seed(),normal(),gamaa(),uniform ya sara method ha random ka
np.random.seed(7)

In [112]:
np.random.normal(size=(3,3))

array([[ 1.69052570e+00, -4.65937371e-01,  3.28201637e-02],
       [ 4.07516283e-01, -7.88923029e-01,  2.06557291e-03],
       [-8.90385858e-04, -1.75472431e+00,  1.01765801e+00]])

In [114]:
np.random.uniform(size=(3,4))

array([[0.38094113, 0.06593635, 0.2881456 , 0.90959353],
       [0.21338535, 0.45212396, 0.93120602, 0.02489923],
       [0.60054892, 0.9501295 , 0.23030288, 0.54848992]])

In [116]:
x=np.random.randn(4,5)
x

array([[-0.32941375,  0.84073324, -0.1799864 ,  0.56806189, -0.7528372 ],
       [-1.7083392 , -1.80309866,  0.38312185,  2.24759505,  0.26941163],
       [-0.52460462,  1.91201886,  0.23730185,  0.10143399,  0.25257774],
       [-0.1323772 , -0.30947634, -1.43496347,  0.50162412, -0.09477545]])

In [117]:
x.reshape(2,2,5) # by default row major order ma save karaga 

array([[[-0.32941375,  0.84073324, -0.1799864 ,  0.56806189,
         -0.7528372 ],
        [-1.7083392 , -1.80309866,  0.38312185,  2.24759505,
          0.26941163]],

       [[-0.52460462,  1.91201886,  0.23730185,  0.10143399,
          0.25257774],
        [-0.1323772 , -0.30947634, -1.43496347,  0.50162412,
         -0.09477545]]])

In [119]:
x.reshape(2,2,5,order='F') # YAHA column major order bataya ha 

array([[[-0.32941375,  0.84073324, -0.1799864 ,  0.56806189,
         -0.7528372 ],
        [-0.52460462,  1.91201886,  0.23730185,  0.10143399,
          0.25257774]],

       [[-1.7083392 , -1.80309866,  0.38312185,  2.24759505,
          0.26941163],
        [-0.1323772 , -0.30947634, -1.43496347,  0.50162412,
         -0.09477545]]])

In [120]:
x.reshape(2,2,-1) # 1 dimension skip

array([[[-0.32941375,  0.84073324, -0.1799864 ,  0.56806189,
         -0.7528372 ],
        [-1.7083392 , -1.80309866,  0.38312185,  2.24759505,
          0.26941163]],

       [[-0.52460462,  1.91201886,  0.23730185,  0.10143399,
          0.25257774],
        [-0.1323772 , -0.30947634, -1.43496347,  0.50162412,
         -0.09477545]]])

In [125]:
x


array([[-0.32941375,  0.84073324, -0.1799864 ,  0.56806189, -0.7528372 ],
       [-1.7083392 , -1.80309866,  0.38312185,  2.24759505,  0.26941163],
       [-0.52460462,  1.91201886,  0.23730185,  0.10143399,  0.25257774],
       [-0.1323772 , -0.30947634, -1.43496347,  0.50162412, -0.09477545]])

In [122]:
x.ravel() #1 dimension hogaya ha 

array([-0.32941375,  0.84073324, -0.1799864 ,  0.56806189, -0.7528372 ,
       -1.7083392 , -1.80309866,  0.38312185,  2.24759505,  0.26941163,
       -0.52460462,  1.91201886,  0.23730185,  0.10143399,  0.25257774,
       -0.1323772 , -0.30947634, -1.43496347,  0.50162412, -0.09477545])

In [124]:
x.flatten()

array([-0.32941375,  0.84073324, -0.1799864 ,  0.56806189, -0.7528372 ,
       -1.7083392 , -1.80309866,  0.38312185,  2.24759505,  0.26941163,
       -0.52460462,  1.91201886,  0.23730185,  0.10143399,  0.25257774,
       -0.1323772 , -0.30947634, -1.43496347,  0.50162412, -0.09477545])

In [ ]:
#CONCATINATE 0 MEAN 0 1 MEAN COLUMN ROW WISE CONCATINATE MA ROW BARHA GI COLUMN WISE MA COLUMN IS KA AUR BI FUNC HA 
# VSTACK HSTACK

In [126]:
x=[[1,3,4],[5,6,7]]

In [127]:
arr1=np.array(x)

In [128]:
y=[[11,12,45],[5,6,5]]

In [129]:
arr2=np.array(y)

In [131]:
np.concatenate((arr1,arr2),axis=0)

array([[ 1,  3,  4],
       [ 5,  6,  7],
       [11, 12, 45],
       [ 5,  6,  5]])

In [132]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  3,  4, 11, 12, 45],
       [ 5,  6,  7,  5,  6,  5]])

In [133]:
np.vstack((arr1,arr2)) #row wise axis define ki zarwt nhi

array([[ 1,  3,  4],
       [ 5,  6,  7],
       [11, 12, 45],
       [ 5,  6,  5]])

In [134]:
np.hstack((arr1,arr2)) #column  wise

array([[ 1,  3,  4, 11, 12, 45],
       [ 5,  6,  7,  5,  6,  5]])

In [135]:
#split 1 array ko different pieces ma break karta ha 
x=[1,2,3,4,5,6,7]

In [136]:
y=np.array(x)

In [137]:
np.split(y,[2,5]) #2,5 mean 2 aur 5 possition pa break

[array([1, 2]), array([3, 4, 5]), array([6, 7])]

In [149]:
x=[[1,4,5,6,7,9,1,4],[11,14,15,16,17,19,11,14]]
x

[[1, 4, 5, 6, 7, 9, 1, 4], [11, 14, 15, 16, 17, 19, 11, 14]]

In [146]:
y=np.array(x)
y

array([[ 1,  4,  5,  6,  7,  9,  1,  4],
       [11, 14, 15, 16, 17, 19, 11, 14]])

In [148]:
np.split(y,[4,6],axis=1) # 2 aur 3 column pa split hoa ha 

[array([[ 1,  4,  5,  6],
        [11, 14, 15, 16]]), array([[ 7,  9],
        [17, 19]]), array([[ 1,  4],
        [11, 14]])]

In [159]:
np.split(y,[1],axis=0)  # row 2 hiso ma toot gaye ha 
#vsplit aur hsplit bi use hota ha

[array([[1, 4, 5, 6, 7, 9, 1, 4]]), array([[11, 14, 15, 16, 17, 19, 11, 14]])]

In [160]:
d=np.array([1,2,3])

In [162]:
np.repeat(d,2) # haar element 2 baar repeat

array([1, 1, 2, 2, 3, 3])

In [164]:
np.tile(d,2) # ya pori list repeat

array([1, 2, 3, 1, 2, 3])