In [2]:
import numpy as n

In [42]:
mylist=list(range(1000000))

In [18]:
type(mylist)

list

In [22]:
mylist1=n.arange(1000000) #numpy ka function ha ya 

In [23]:
type(mylist)

numpy.ndarray

In [27]:
n.arange(10) #range create karta ho ya bi numpy ka function

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
n.arange(10).ndim


1

In [43]:
%time
for _ in range(10000):
    myarray2=mylist*2
    

Wall time: 0 ns


KeyboardInterrupt: 

In [11]:
data =n.random.randn(2,3)
data

array([[ 0.75041475, -0.28679006, -0.11575623],
       [ 1.34984896, -1.30778778,  0.86432945]])

In [25]:
data.ndim #dimension 2 ha ya function bata raha ha dimension is a exxess
# 4th dimension ma pic ki example ha xaxis 1 dimension y 2 aur chaneel 3 tu ya ak pecha ak 4th dimension hjaega

2

In [10]:
data =n.random.randn(5,3,3)
data 
#dimension ka pecha ak ka pecha ak lag jaye tu queeb ban jata ha 3d first parameter x axis nhi ha depth ha means ak ka pecha ak.

array([[[ 0.82379599, -0.48646316, -0.65069635],
        [-0.31380098,  0.95620089,  0.03161805],
        [-1.77379239,  2.39593205,  0.35675073]],

       [[ 2.10061053, -0.58160426, -0.10256085],
        [ 0.78741295, -0.65980365,  2.7635749 ],
        [ 0.58895135, -1.16694831,  0.16983879]],

       [[-0.73659318, -0.69092125, -0.9356503 ],
        [-0.64989373, -0.34336952,  1.64569737],
        [ 0.2839853 ,  2.71118695,  0.3960766 ]],

       [[-2.31678646, -0.62853383, -0.80498095],
        [-0.67765197,  0.07740628,  0.50951926],
        [-0.0970676 ,  0.89316582, -1.31906434]],

       [[-0.95821178, -0.97225046,  0.41108745],
        [-1.08446085,  0.04798737, -0.57836   ],
        [-1.42233084,  0.3054016 ,  0.20247287]]])

In [9]:
data.ndim

3

In [5]:
d=n.random.randn(2,2) # numpy ka function ha
d

array([[-0.58498499, -0.77238427],
       [-0.07806679,  0.87141908]])

In [13]:
d*10 

array([[-10.9802306 ,  13.75958866],
       [ 13.73175274, -12.37796251]])

In [18]:
f=n.random.randn(2,2)
f

array([[-0.39177097, -0.62864932],
       [ 0.47868338, -0.49274382]])

In [19]:
f/10

array([[-0.0391771 , -0.06286493],
       [ 0.04786834, -0.04927438]])

In [20]:
f+d  # this is fast vectorize rows aur column same hona chaye jitna bi operation perform kiya ha mirrror addition,multiplication.programing ma element wise bolta ha

array([[-1.48979403,  0.74730955],
       [ 1.85185866, -1.73054007]])

In [ ]:
#phle matrix ki column aur dosri ki row barabar hona chaye

In [21]:
d.shape  #matrix ka bataraha 3*3 ha ya 2*2

(2, 2)

In [22]:
n.dot(d,f) #matrix multiplication ya numpy ka ha

array([[ 1.0888222 ,  0.01227622],
       [-1.1304827 , -0.25332925]])

In [23]:
d@f  #matrix multiplication ya python ka

array([[ 1.0888222 ,  0.01227622],
       [-1.1304827 , -0.25332925]])

In [25]:
d.dot(f) #matrix multiplication ya python ka ha

array([[ 1.0888222 ,  0.01227622],
       [-1.1304827 , -0.25332925]])

In [26]:
n.zeros(10) # ya vector ki form ma da raha ha 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
n.zeros((10,10)) # ya matrix ki form

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
n.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#one hot encoding bi ata ha kam ha isma 0 aur 1 hota ha
#asarrry data type change karna ka liya

In [32]:
n.empty((5,5)) # ya memory ki garbage value ko bi la ata ha isliye o nhi aya yaha.

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
print(d.shape)
print(d.dtype)
n.ones_like(d)

(2, 2)
float64


array([[1., 1.],
       [1., 1.]])

In [36]:
#ones like ya produuce sara 1 kara ga aur ya ap sa data type aur shape nhi pucha ga 

print(d.shape)
print(d.dtype)
n.ones_like(d)

(2, 2)
float64


array([[1., 1.],
       [1., 1.]])

In [37]:
n.ones((2,2),dtype='uint8')

array([[1, 1],
       [1, 1]], dtype=uint8)

In [38]:
n.ones_like(d)

array([[1., 1.],
       [1., 1.]])

In [3]:
n.full((2,2),5) # sara member 5 honga ya bi numpy ka function

array([[5, 5],
       [5, 5]])

In [6]:
n.full_like(d,5) # ya bi ak aur tarika ha ya bi numpy ka function ha

array([[5., 5.],
       [5., 5.]])

In [7]:
arr1=n.array([1,2,3],dtype=n.float32)
arr1 # ya array define ka sath uski data type bi bata raha ha

array([1., 2., 3.], dtype=float32)

In [10]:
arr1=n.array([1,2,3],dtype='float32')
arr1

array([1., 2., 3.], dtype=float32)

In [11]:
type(arr1)

numpy.ndarray

In [12]:
arr1.astype(n.int) #type change karna ka liya 

array([1, 2, 3])

In [21]:
numeric_string=n.array(['1.3','7.6','6.7'],dtype=n.string_)

In [24]:
type(numeric_string)

numpy.ndarray

In [23]:
numeric_string.astype(n.float)

array([1.3, 7.6, 6.7])

In [25]:
type(numeric_string)

numpy.ndarray

In [14]:
a=n.random.randn(2,2) # numpy ka function ha
a

array([[-2.37002756,  0.63406834],
       [-0.78626262, -0.15356057]])

In [15]:
b=n.random.randn(2,2) # numpy ka function ha
b

array([[ 0.02871284,  1.51080325],
       [-2.16543271,  1.34361127]])

In [16]:
a>b


array([[False, False],
       [ True, False]])

In [ ]:
#jb index kar ka koi value lata ha tu matrix ki value ati ha slice karta wakta us matrix ka part ata ha

In [18]:
a=[1,2,3,4]

In [19]:
a[2]

3

In [28]:
type(a)

list

In [27]:
type(a[2])

int

In [32]:
type(a[0:1])

list

In [33]:
a=n.array([2]).ndim

1

In [38]:
a=n.array([[2]]).ndim


In [40]:
b=n.array([1,4,5,6,7])  #vector ki term ma 5 dimension vector lakin agr tensor ya matrix ki form ma baat kara tu 1 dimension ha 

In [41]:
b.shape
# 1 dimension ka out asa aye ga , means ya vector ha

(5,)

In [45]:
a=n.array([[[2]]])

In [46]:
a.shape #jitne bracket lagao utni dimesion barhagi

(1, 1, 1)

In [47]:
a.ndim #more than one vector is a matrix haar row ak vector ha matrix ma

3

In [48]:
a=n.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
a[1][2] #indexing

6

In [50]:
 #not value 2 dimension array

array([[6]])

In [51]:
a[0:2,2:]

array([[2, 3],
       [6, 7]])

In [52]:
a[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [54]:
a[1::,1:3]

array([[ 5,  6],
       [ 9, 10]])